remove tqdm from OpenNEM parser
This was added in #3066, but seems to be causing exceptions fairly
often with message
   AttributeError: 'tqdm' object has no attribute 'pos'

That seems like maybe a weird tqdm bug, maybe related to running parsers
in worker threads (see https://github.com/tqdm/tqdm/issues/323) but the
easiest solution seems to be just to remove tqdm since it's only a
debugging nice-to-have.